[package]
name = "tiny-clippy"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
image = "0.24"
rand = "0.8.5"
eframe = "0.29.1"